version: '2'

services:
    php:
        build: ./${PHP_VERSION}
        volumes_from:
            - source
        links:
            - db
            - memcached
        networks:
            - bitrix
        restart: always
    web_server:
        build: ./${WEB_SERVER_TYPE}
        depends_on:
            - source
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:80:80'
            - '${INTERFACE}:443:443'
        links:
            - php
        networks:
            - bitrix
        restart: always
    db:
        build: ./${DB_SERVER_TYPE}
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:3306:3306'
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        command: mysqld --sql-mode=""
        networks:
            - bitrix
        restart: always
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
         - PMA_ARBITRARY=1
        restart: always
        ports:
            - 8081:80
        depends_on:
            - db
        environment:
          PMA_HOST: db
        networks:
         - bitrix
    memcached:
        image: memcached:1.6.12-alpine
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:11211:11211'
        networks:
            - bitrix
        restart: always
    adminer:
        image: dockette/adminer:full
        links:
            - db:db
        ports:
            - '${INTERFACE}:8080:80'
        environment:
            UPLOAD: 1024M # upload_max_filesize, post_max_size
        networks:
            - bitrix
    zookeeper:
        image: wurstmeister/zookeeper
        restart: always
        ports:
          - 2181:2181
        networks:
          - bitrix
    kafka:
        image: wurstmeister/kafka
        ports:
          - 9092:9092
        restart: always
        depends_on:
          - zookeeper
        environment:
          KAFKA_ADVERTISED_HOST_NAME: kafka
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_CREATE_TOPICS: "test:1:1,products:1:1:compact,vendors:1:1:compact, prices:1:1:compact,warehouses:1:1:compact,priceTypes:1:1:compact,stocks:1:1:compact,answers:1:1:compact"          
        networks:
          - bitrix
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./kafka:/kafka
    kafka-ui:
        image: provectuslabs/kafka-ui
        container_name: kafka-ui
        ports:
          - "7989:8080"
        restart: always
        environment:
          KAFKA_CLUSTERS_0_NAME: local
          KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
          KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
          KAFKA_CLUSTERS_0_READONLY: "false"
          AUTH_TYPE: "LOGIN_FORM"
          SPRING_SECURITY_USER_NAME: root
          SPRING_SECURITY_USER_PASSWORD: root
        volumes:  
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
          - bitrix
    source:
        image: alpine:latest
        volumes:
            - ./logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
            - ./logs/php:/var/log/php
            - ./logs/db:/var/log/mysql
            - ./logs/memcached:/var/log/memcached
            - db:/var/lib/mysql
            - cache:/var/lib/memcached
            - ./www/html:/var/www/html
            - ${ROOT_PATH}:/var/www/sites
            - /etc/localtime:/etc/localtime/:ro
        networks:
            - bitrix

volumes:
    db:
        driver: local
    cache:
        driver: local

networks:
    bitrix:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.100.0.0/24
